export const PRODUCT_STATUS_MAP = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  REMOVED: 'REMOVED'
} as const;

export const PRODUCT_EXIST_STATUS = [PRODUCT_STATUS_MAP.AVAILABLE, PRODUCT_STATUS_MAP.UNAVAILABLE] as const;
