AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    Microservice:
        Type: String
    SubnetIdsList:
        Type: List<AWS::EC2::Subnet::Id>
    SecurityGroupIdList:
        Type: List<AWS::EC2::SecurityGroup::Id>

Resources:
    SecretManager:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db
            GenerateSecretString:
                SecretStringTemplate: !Sub '{"username": "${Microservice}"}'
                GenerateStringKey: "password"
                PasswordLength: 30
                ExcludeCharacters: '"@/\'
            Tags:
              - Key: Service
                Value: SecretsManager
              - Key: Resource
                Value: Secret
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-document-db

    Parameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db
            Tags:
                Service: SSM
                Resource: Parameter
                Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db
                StackName: !Ref AWS::StackName
                StackId: !Ref AWS::StackId
                Region: !Ref AWS::Region
                Microservice: !Ref Microservice
                Stage: !Ref Stage
                Tenant: !Ref Tenant
            Type: String
            Value:
                Fn::ToJsonString:
                    database: !Ref Microservice
                    host: !Sub
                      - ${Endpoint}:${Port}
                      - Endpoint: !GetAtt Cluster.Endpoint
                        Port: !GetAtt Cluster.Port
                    protocol: mongodb
                    options:
                        retryWrites: false
                        readPreference: secondaryPreferred
                        replicaSet: rs

    ParameterGroup:
        Type: AWS::DocDB::DBClusterParameterGroup
        Properties:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-parameter-group
            Description: !Sub "Parameter group for ${Stage}-${Tenant}-${Microservice}"
            Family: "docdb5.0.0"
            Parameters:
                audit_logs: "disabled"
                tls: "disable"
                ttl_monitor: "disabled"
            Tags:
              - Key: Service
                Value: DocDB
              - Key: Resource
                Value: DBClusterParameterGroup
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-parameter-group

    SubnetGroup:
        Type: AWS::DocDB::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: !Sub "Subnet group for ${Stage}-${Tenant}-${Microservice}"
            DBSubnetGroupName: !Sub ${Stage}-${Tenant}-${Microservice}-subnet-group
            SubnetIds: !Ref SubnetIdsList
            Tags:
              - Key: Service
                Value: DocDB
              - Key: Resource
                Value: DBSubnetGroup
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-subnet-group

    Cluster:
        DependsOn:
          - SecretManager
        Type: AWS::DocDB::DBCluster
        Properties:
            DBClusterIdentifier: !Sub ${Stage}-${Tenant}-${Microservice}
            DBClusterParameterGroupName: !Ref ParameterGroup
            DBSubnetGroupName: !Ref SubnetGroup
            EngineVersion: '5.0.0'
            KmsKeyId: String
            MasterUsername: !Sub '{{resolve:secretsmanager:${Stage}-${Tenant}-${Microservice}-document-db:SecretString:username}}'
            MasterUserPassword: !Sub '{{resolve:secretsmanager:${Stage}-${Tenant}-${Microservice}-document-db:SecretString:password}}'
            BackupRetentionPeriod: 7
            Tags:
              - Key: Service
                Value: DocDB
              - Key: Resource
                Value: DBCluster
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}
            VpcSecurityGroupIds: !Ref SecurityGroupIdList

    DBInstance:
        Type: "AWS::DocDB::DBInstance"
        Properties:
            DBClusterIdentifier: !Ref Cluster
            DBInstanceClass: db.t3.medium
            DBInstanceIdentifier: !Sub ${Stage}-${Tenant}-${Microservice}-db-instance-0
            PreferredMaintenanceWindow: "mon:06:54-mon:07:24"
            Tags:
              - Key: Service
                Value: DocDB
              - Key: Resource
                Value: DBCluster
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-db-instance-0

Outputs:
    Cluster:
        Description: Cluster
        Value: !Ref Cluster
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-cluster
    ClusterEndpoint:
        Description: Cluster Endpoint
        Value: !GetAtt Cluster.Endpoint
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-cluster-endpoint
    ClusterPort:
        Description: Cluster Port
        Value: !GetAtt Cluster.Endpoint
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-cluster-port
    DBInstance:
        Description: DBInstance
        Value: !Ref DBInstance
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-instance
    SubnetGroup:
        Description: SubnetGroup
        Value: !Ref SubnetGroup
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-subnet-group
    ParameterGroup:
        Description: ParameterGroup
        Value: !Ref ParameterGroup
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-db-parameter-group
    SecretManager:
        Description: SecretManager
        Value: !Sub ${Stage}-${Tenant}-${Microservice}-document-db
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-secret
    Parameter:
        Description: Parameter
        Value: !Ref Parameter
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-document-db-parameter
