AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    Microservice:
        Type: String


Conditions:
    IsProdCondition: !Equals [!Ref Stage, "prod"]

Resources:
    DynamoTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub ${Stage}_${Tenant}_${Microservice}_name
            AttributeDefinitions:
              - AttributeName: hash
                AttributeType: S
              - AttributeName: range
                AttributeType: S
            KeySchema:
              - AttributeName: hash
                KeyType: HASH
              - AttributeName: range
                KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            Tags:
              - Key: Service
                Value: DynamoDB
              - Key: Resource
                Value: Table
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}_name
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: !If [IsProdCondition, true, false]
            TimeToLiveSpecification:
                AttributeName: ttl
                Enabled: false
