
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Stage:
        Type: String
        Description: Development stage of repository
    Tenant:
        Type: String
        Description: Project tenant for deployment
        Default: tcc
    Microservice:
        Type: String

Resources:
    Repository:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: !Sub ${Stage}-${Tenant}-${Microservice}
            Tags:
              - Key: Service
                Value: ECR
              - Key: Resource
                Value: Repository
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}

Outputs:
    RepositoryUri:
        Description: The repository uri
        Value: !GetAtt Repository.RepositoryUri
        Export:
            Name: !Sub ${Stage}-${Tenant}-${Microservice}-ecr-repository-uri
