AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
    Stage:
        Type: String
    Tenant:
        Type: String
    Microservice:
        Type: String
    LogLevel:
        Type: String
        AllowedValues:
          - error
          - warn
          - log
          - info
          - verbose
          - debug
Globals:
    Function:
        Timeout: 60
        Runtime: nodejs20.x
        Environment:
            Variables:
                STAGE: !Ref Stage
                TENANT: !Ref Tenant
                REGION: !Ref AWS::Region
                ACCOUNT_NUMBER: !Ref AWS::AccountId
                MICROSERVICE: !Ref Microservice
                EVENT_BUS: { "Fn::ImportValue": !Sub "${Stage}-${Tenant}-event-bus" }
                RDS_SECRET: !Sub "${Stage}-${Tenant}-rds"
                RDS_PARAMS: !Sub "${Stage}-${Tenant}-rds"
                LOG_LEVEL: !Ref LogLevel

Resources:
    LambdaRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: !Sub ${AWS::StackName}-lambda-role
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Principal:
                        Service:
                          - "lambda.amazonaws.com"
                          - "events.amazonaws.com"
                    Action:
                      - "sts:AssumeRole"
            Path: "/"
            ManagedPolicyArns:
              - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
              - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
              - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
              - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
            Policies:
              - PolicyName: !Sub ${AWS::StackName}
                PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: "Allow"
                        Action:
                          - lambda:PublishVersion
                          - lambda:InvokeFunction
                          - apigateway:*
                        Resource: "*"
            Tags:
              - Key: Service
                Value: IAM
              - Key: Resource
                Value: Role
              - Key: Name
                Value: !Sub ${AWS::StackName}-lambda-role
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice

    QueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            Queues:
              - !Ref ReturnToStockSQS
              - !Ref SellSQS
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Sid: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock-sqs
                    Effect: Allow
                    Action:
                      - sqs:SendMessage
                    Principal:
                        Service:
                          - "sns.amazonaws.com"
                    Resource: !GetAtt ReturnToStockSQS.Arn
                    Condition:
                        ArnEquals:
                            aws:SourceArn:
                                Fn::ImportValue: !Sub ${Stage}-${Tenant}-event-bus
                  - Sid: !Sub ${Stage}-${Tenant}-${Microservice}-sell-sqs
                    Effect: Allow
                    Action:
                      - sqs:SendMessage
                    Principal:
                        Service:
                          - "sns.amazonaws.com"
                    Resource: !GetAtt SellSQS.Arn
                    Condition:
                        ArnEquals:
                            aws:SourceArn:
                                Fn::ImportValue: !Sub ${Stage}-${Tenant}-event-bus

    ReturnToStock:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock
            Role: !GetAtt LambdaRole.Arn
            CodeUri: ./../
            Handler: dist/handlers/returnToStock.returnToStock
            VpcConfig:
                SubnetIds: !Split [',', {'Fn::ImportValue': !Sub "${Stage}-${Tenant}-private-subnets-list"}]
                SecurityGroupIds: 
                  - Fn::ImportValue: !Sub "${Stage}-${Tenant}-private-subnet-security-group-id"
            Tags:
                Service: Serverless
                Resource: Function
                Name: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock
                StackName: !Ref AWS::StackName
                StackId: !Ref AWS::StackId
                Region: !Ref AWS::Region
                Microservice: !Ref Microservice
                Stage: !Ref Stage
                Tenant: !Ref Tenant                    
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt ReturnToStockSQS.Arn
                        BatchSize: 1
            Tracing: PassThrough

    ReturnToStockLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /aws/lambda/${ReturnToStock}
            RetentionInDays: 1
            Tags:
              - Key: Service
                Value: CloudWatch
              - Key: Resource
                Value: LogGroup
              - Key: Name
                Value: !Sub /aws/lambda/${ReturnToStock}
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice

    ReturnToStockSQS:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock-sqs
            DelaySeconds: 0
            VisibilityTimeout: 60
            ReceiveMessageWaitTimeSeconds: 1
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt ReturnToStockDLQ.Arn
                maxReceiveCount: 5
            Tags:
              - Key: Service
                Value: SQS
              - Key: Resource
                Value: Queue
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock-sqs
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice


    ReturnToStockDLQ:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock-dlq
            DelaySeconds: 0
            VisibilityTimeout: 60
            ReceiveMessageWaitTimeSeconds: 1
            Tags:
              - Key: Service
                Value: SQS
              - Key: Resource
                Value: Queue
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-return-to-stock-dlq
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice

    ReturnToStockSNSSubscription:
        Type: 'AWS::SNS::Subscription'
        Properties:
            TopicArn:
                Fn::ImportValue: !Sub ${Stage}-${Tenant}-event-bus
            Endpoint: !GetAtt ReturnToStockSQS.Arn
            Protocol: sqs
            FilterPolicy: '{"type": ["rejected"], "status": ["success"], "event": ["orders"]}'


    Sell:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Stage}-${Tenant}-${Microservice}-sell
            Role: !GetAtt LambdaRole.Arn
            CodeUri: ./../
            Handler: dist/handlers/returnToStock.returnToStock
            VpcConfig:
                SubnetIds: !Split [',', {'Fn::ImportValue': !Sub "${Stage}-${Tenant}-private-subnets-list"}]
                SecurityGroupIds: 
                  - Fn::ImportValue: !Sub "${Stage}-${Tenant}-private-subnet-security-group-id"
            Tags:
                Service: Serverless
                Resource: Function
                Name: !Sub ${Stage}-${Tenant}-${Microservice}-sell
                StackName: !Ref AWS::StackName
                StackId: !Ref AWS::StackId
                Region: !Ref AWS::Region
                Microservice: !Ref Microservice
                Stage: !Ref Stage
                Tenant: !Ref Tenant                    
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SellSQS.Arn
                        BatchSize: 1
            Tracing: PassThrough

    SellLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /aws/lambda/${Sell}
            RetentionInDays: 1
            Tags:
              - Key: Service
                Value: CloudWatch
              - Key: Resource
                Value: LogGroup
              - Key: Name
                Value: !Sub /aws/lambda/${Sell}
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice

    SellSQS:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub ${Stage}-${Tenant}-${Microservice}-sell-sqs
            DelaySeconds: 0
            VisibilityTimeout: 60
            ReceiveMessageWaitTimeSeconds: 1
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt SellDLQ.Arn
                maxReceiveCount: 5
            Tags:
              - Key: Service
                Value: SQS
              - Key: Resource
                Value: Queue
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-sell-sqs
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice

    SellDLQ:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub ${Stage}-${Tenant}-${Microservice}-sell-dlq
            DelaySeconds: 0
            VisibilityTimeout: 60
            ReceiveMessageWaitTimeSeconds: 1
            Tags:
              - Key: Service
                Value: SQS
              - Key: Resource
                Value: Queue
              - Key: Name
                Value: !Sub ${Stage}-${Tenant}-${Microservice}-sell-dlq
              - Key: Stage
                Value: !Ref Stage
              - Key: Tenant
                Value: !Ref Tenant
              - Key: StackName
                Value: !Ref AWS::StackName
              - Key: StackId
                Value: !Ref AWS::StackId
              - Key: Region
                Value: !Ref AWS::Region
              - Key: Microservice
                Value: !Ref Microservice

    SellSNSSubscription:
        Type: 'AWS::SNS::Subscription'
        Properties:
            TopicArn:
                Fn::ImportValue: !Sub ${Stage}-${Tenant}-event-bus
            Endpoint: !GetAtt SellSQS.Arn
            Protocol: sqs
            FilterPolicy: '{"type": ["approved"], "status": ["success"], "event": ["orders"]}'
